### ISSUE TITLE
Please consider updating the README to include instructions for installing 'z'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [dcervenkov/ulauncher-z-search#2]
I'd like to try your extension. I'd like to do so with `z` installed. However, I can't find how to install `z`. I am on Mint 19.3 x64 Cinnamon. I have failed to find `z` in my repositories or indeed anywhere else. Thanks.

**Comment by dcervenkov** [comment]
`z` is just a simple shell script that you have to source. You can download it from [Github](https://github.com/rupa/z) and source it in your `.bashrc`/`.zshrc`/whatever `bash` compatible shell you use. You can find more specific info on installation in the `z.sh` itself.

To summarize:
1. `wget https://raw.githubusercontent.com/rupa/z/master/z.sh -O /path/to/new/z.sh`
2. Add `source /path/to/new/z.sh` (or `. /path/to/new/z.sh`) to your `.bashrc`
3. Start using `cd` from the command line to build up your `.z` file
4. Once you've `cd`d into a path, both `z` and my extension will be able to find it

**Comment by LinuxOnTheDesktop** [comment]
Thsnk you. That seems to work. I note the following. Even if one puts `z.sh` somewhere other thsn `~`, the `.z` file is in `~` (which I am fine with;[1] I note the location of the `.z` file because your Ulauncher extension asks for that location).

If you move what you posted to your README, or even perhaps just tag this 'issue' as a 'question' or 'documentation', then I'll close this issue.

[1] Actually, it would be neater for it to be in `~/.config/z/`. It looks like I'd have to hack `z.sh` to make that so.

**Comment by dcervenkov** [comment]
The location of the `.z` file is selectable because one can change it in `z.sh` as well by setting the `_Z_DATA` environment variable. This is documented in the `z.sh` readme.

I'm reluctant to add `z.sh` installation steps to my readme, as those are outside of my control and can change. But I've added a direct link to the script header with the steps.
